name: flutter_app_badger
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 1.6.0
homepage: https://github.com/g123k/flutter_app_badger

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.flutterappbadger
        pluginClass: FlutterAppBadgerPlugin
      ios:
        pluginClass: FlutterAppBadgerPlugin
      macos:
        pluginClass: FlutterAppBadgerPlugin
